# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subsequencesMatrixCpp <- function(values, subsequenceWidth) {
    .Call(`_RcppShapeDTW_subsequencesMatrixCpp`, values, subsequenceWidth)
}

asShapeDescriptorCpp <- function(subsequenceSeries, shapeDescriptorParams) {
    .Call(`_RcppShapeDTW_asShapeDescriptorCpp`, subsequenceSeries, shapeDescriptorParams)
}

trigonometicTransformCpp <- function(input, transformType) {
    .Call(`_RcppShapeDTW_trigonometicTransformCpp`, input, transformType)
}

TSNormalizationCpp <- function(input, normType) {
    .Call(`_RcppShapeDTW_TSNormalizationCpp`, input, normType)
}

RcpptsTransformation <- function(timeSeries, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams = NULL) {
    .Call(`_RcppShapeDTW_RcpptsTransformation`, timeSeries, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams)
}

RcppDistanceMatrices <- function(timeSeriesRef, timeSeriesTest, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams = NULL, distanceType = "Dependent") {
    .Call(`_RcppShapeDTW_RcppDistanceMatrices`, timeSeriesRef, timeSeriesTest, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams, distanceType)
}

RcppAccumulatedCostMatrix <- function(x) {
    .Call(`_RcppShapeDTW_RcppAccumulatedCostMatrix`, x)
}

RcppSimpleDTW <- function(x) {
    .Call(`_RcppShapeDTW_RcppSimpleDTW`, x)
}

RcppdistanceFromWarpingPaths <- function(distMatrix, path1, path2) {
    .Call(`_RcppShapeDTW_RcppdistanceFromWarpingPaths`, distMatrix, path1, path2)
}

RcppComplexDTWResults <- function(RawSeriesDistMat, ShapeDescriptorMatrix, DistanceType = "Dependent") {
    .Call(`_RcppShapeDTW_RcppComplexDTWResults`, RawSeriesDistMat, ShapeDescriptorMatrix, DistanceType)
}

kNNShapeDTWCpp <- function(referenceSeries, testSeries, forecastHorizon, subsequenceWidth, subsequenceBreaks, shapeDescriptorParams, normalizationType = "Unitarization", distanceType = "Dependent", ttParams = NULL) {
    .Call(`_RcppShapeDTW_kNNShapeDTWCpp`, referenceSeries, testSeries, forecastHorizon, subsequenceWidth, subsequenceBreaks, shapeDescriptorParams, normalizationType, distanceType, ttParams)
}

rcpp_hello_world <- function() {
    .Call(`_RcppShapeDTW_rcpp_hello_world`)
}

