# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppsubsequencesMatrix <- function(values, subsequenceWidth) {
    .Call(`_RcppShapeDTW_RcppsubsequencesMatrix`, values, subsequenceWidth)
}

RcppasShapeDescriptor <- function(subsequenceSeries, shapeDescriptorParams) {
    .Call(`_RcppShapeDTW_RcppasShapeDescriptor`, subsequenceSeries, shapeDescriptorParams)
}

RcpptrigonometicTransform <- function(input, transformType) {
    .Call(`_RcppShapeDTW_RcpptrigonometicTransform`, input, transformType)
}

RcppTSNormalization <- function(input, normType) {
    .Call(`_RcppShapeDTW_RcppTSNormalization`, input, normType)
}

RcpptsTransformation <- function(timeSeries, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams = NULL) {
    .Call(`_RcppShapeDTW_RcpptsTransformation`, timeSeries, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams)
}

RcppDistanceMatrices <- function(timeSeriesRef, timeSeriesTest, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams = NULL, distanceType = "Dependent") {
    .Call(`_RcppShapeDTW_RcppDistanceMatrices`, timeSeriesRef, timeSeriesTest, shapeDescriptorParams, subsequenceWidth, normalizationType, trigonometricTransformParams, distanceType)
}

RcppAccumulatedCostMatrix <- function(x, sakoeChibaWindow = NULL) {
    .Call(`_RcppShapeDTW_RcppAccumulatedCostMatrix`, x, sakoeChibaWindow)
}

RcppSimpleDTW <- function(x, sakoeChibaWindow = NULL) {
    .Call(`_RcppShapeDTW_RcppSimpleDTW`, x, sakoeChibaWindow)
}

RcppdistanceFromWarpingPaths <- function(distMatrix, path1, path2) {
    .Call(`_RcppShapeDTW_RcppdistanceFromWarpingPaths`, distMatrix, path1, path2)
}

RcppComplexDTWResults <- function(RawSeriesDistMat, ShapeDescriptorMatrix, DistanceType = "Dependent", sakoeChibaWindow = NULL) {
    .Call(`_RcppShapeDTW_RcppComplexDTWResults`, RawSeriesDistMat, ShapeDescriptorMatrix, DistanceType, sakoeChibaWindow)
}

kNNShapeDTWCpp <- function(referenceSeries, testSeries, forecastHorizon, subsequenceWidth, subsequenceBreaks, shapeDescriptorParams, normalizationType = "Unitarization", distanceType = "Dependent", ttParams = NULL, sakoeChibaWindow = NULL) {
    .Call(`_RcppShapeDTW_kNNShapeDTWCpp`, referenceSeries, testSeries, forecastHorizon, subsequenceWidth, subsequenceBreaks, shapeDescriptorParams, normalizationType, distanceType, ttParams, sakoeChibaWindow)
}

rcpp_hello_world <- function() {
    .Call(`_RcppShapeDTW_rcpp_hello_world`)
}

